---
title: "Cleaning"
author: "gif or gif"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
#data
CHECK_EOC <- read.csv("data/checkpoints_eoc.csv")
PAGE_VIEW <- read.csv("data/page_views.csv")
```

#creating full table

```{r}
filtered_eoc <- CHECK_EOC %>%
  mutate(avg_attempt = n_attempt/n_possible) %>% #creating metric to see how many attempts per possible question there are
  filter(book == "College / Statistics and Data Science (ABC)", !is.na(EOC)) %>% #filtering by book with largest amount of data
  select(-c(n_possible,n_correct,n_attempt,book)) 

filtered_views <- PAGE_VIEW %>% 
  filter(book == "College / Statistics and Data Science (ABC)") %>%
  mutate(idle = idle_brief + idle_long) %>% #combining both similar time columns
  mutate(off_page = off_page_brief + off_page_long) %>% #combining both similar time columns
  select(student_id, chapter_number, institution_id, release, engaged, idle, off_page, tried_again_clicks) %>%
  group_by(student_id, institution_id, chapter_number, release) %>%
  summarise(engaged_sum = sum(engaged, na.rm = T) / 60000, #convert to minutes from milliseconds
            idle_sum = sum(idle, na.rm = T) / 60000, #convert to minutes from milliseconds
            off_page_sum = as.numeric(format(sum(off_page, na.rm = T) / 60000, scientific = F)), #convert to minutes from milliseconds, also removed an issue with scientific notation
            tried_again_clicks_sum = sum(tried_again_clicks, na.rm = T))

DATA <- left_join(filtered_eoc,filtered_views, by = c("student_id","chapter_number")) # final table

#renaming institutions and classes
DATA <- DATA %>%
  mutate(institution_id = case_when(institution_id == "04157183-8665-400a-925d-3bbb70ffe45e" ~ "I-01",
                                    institution_id == "292cff87-3c74-4e94-8622-233afb0427dd" ~ "I-02",
                                    institution_id == "364da48a-e0b2-4507-bc31-e7761fe16e95" ~ "I-03",
                                    institution_id == "94a809a9-a0ef-4c47-8d96-3a5ad76f674b" ~ "I-04",
                                    institution_id == "97aebe75-a051-4bff-a2c0-1d53eb5d9498" ~ "I-05",
                                    institution_id == "d2e6c885-36f4-48b9-988b-42eef1f8ed9d" ~ "I-06",
                                    institution_id == "f17495c5-e105-492d-878a-07a03ea3f805" ~ "I-07",
                                    institution_id == "fc5f1b1b-2aeb-4e09-93fc-06fdac0d8030" ~ "I-08")) %>%
  mutate(class_id = case_when(class_id == "0089dedf-6316-4c32-a38c-d48dfafed882" ~ "C-01",
                              class_id == "074123e7-cd90-4500-86fe-286aaa733bf5" ~ "C-02",
                              class_id == "0d546479-6f77-4477-9c7e-365cd36c97eb" ~ "C-03",
                              class_id == "1020418a-3eeb-4251-88f7-150c8fe00a56" ~ "C-04",
                              class_id == "103f5ce8-9e95-4916-815e-9f821d274a59" ~ "C-05",
                              class_id == "1cca9f91-5c4a-4e1a-8e0e-293b070dfd6f" ~ "C-06",
                              class_id == "20bd524c-bb2d-4b74-a419-929475b91d94" ~ "C-07",
                              class_id == "2294d558-6f5d-41c5-8d28-7b5280970f95" ~ "C-08",
                              class_id == "3631cec9-51d3-4237-906f-a142a715be51" ~ "C-09",
                              class_id == "40e49bfa-f6cb-42fa-a3a4-b23592b799ec" ~ "C-10",
                              class_id == "4a3b5b2c-ef0f-4121-96f4-fd8a42764836" ~ "C-11",
                              class_id == "51711479-441b-4c02-aef7-517aca63a53f" ~ "C-12",
                              class_id == "52619962-72f6-4716-9c64-1c06fe10f739" ~ "C-13",
                              class_id == "552ede8f-6b54-426d-8d29-abdc43a668cb" ~ "C-14",
                              class_id == "5bd961c4-659c-40a7-a685-6735189f2b65" ~ "C-15",
                              class_id == "60e05fa5-c986-4973-9833-16238720b727" ~ "C-16",
                              class_id == "65246c1e-a176-4760-acb5-a320a9b7b2fe" ~ "C-17",
                              class_id == "686478e7-82ac-4e6c-a3ec-2da0076ef868" ~ "C-18",
                              class_id == "79662249-02f6-48d8-aa99-1e1c0aeea77d" ~ "C-19",
                              class_id == "7a987176-7e55-45b5-a715-7f56c59d5f49" ~ "C-20",
                              class_id == "822d72d9-0c18-47a0-99fc-7223b4fd22f5" ~ "C-21",
                              class_id == "8589cd83-192c-44c8-b649-cd848e519530" ~ "C-22",
                              class_id == "94da41a4-f9f8-4225-bf41-42db737850b9" ~ "C-23",
                              class_id == "97c61e74-5a20-4cf5-bf67-8f8db750d0e7" ~ "C-24",
                              class_id == "98119d92-8cc6-416a-972c-630351726223" ~ "C-25",
                              class_id == "9bdf8bfc-9998-4fd8-85d2-70c91cf94891" ~ "C-26",
                              class_id == "9fad0c9e-9d3d-4eed-ada6-3959bd6d712c" ~ "C-27",
                              class_id == "afcb6b4e-a0c0-46ce-b38c-c96329c91471" ~ "C-28",
                              class_id == "b1421b49-4026-4c61-9786-d4ef110c8db3" ~ "C-29",
                              class_id == "b16b895d-ca1d-4330-a36d-c43fb33436e5" ~ "C-30",
                              class_id == "bc650f4f-11f0-439a-a90a-47726724c811" ~ "C-31",
                              class_id == "bcae937d-c95f-436c-ac0f-d4a5e995de19" ~ "C-32",
                              class_id == "c09145c1-d635-41ae-b881-17ab46895fe4" ~ "C-33",
                              class_id == "c1168ee3-7ac8-4fdc-af0e-e375ad0629fe" ~ "C-34",
                              class_id == "c7008a64-b43c-4eb4-bebf-07b08b9894ad" ~ "C-35",
                              class_id == "cc1ffb2e-5555-4109-8ad8-2d49cb54ad10" ~ "C-36",
                              class_id == "d0b4f5e2-6d8f-4828-91cd-3f4714b821b0" ~ "C-37",
                              class_id == "fe8c4185-7e8d-48eb-bf0e-85562e060d5d" ~ "C-38"))

# making cat. grade var.
DATA$grade <- ifelse(DATA$EOC > .90, "A",
                   ifelse(DATA$EOC >= .80, "B",
                          ifelse(DATA$EOC >= .70, "C",
                                 ifelse(DATA$EOC >= .60, "D", "F")
                                        )))

# making bin. grade var for model
DATA$success <- ifelse(DATA$EOC > .6, "P", "F")
```

### changing var types

```{r}
DATA <- DATA %>% 
  mutate_if(is.character, as.factor) %>%
  mutate(chapter_number = as.factor(chapter_number))
```


```{r}
save(DATA, file = "data/data.Rdata")
```
