---
title: "Models"
author: "gif or gif"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#libs
library(janitor)
library(tidyverse)
library(tidymodels)
library(caret)
library(pROC)
library(data.table)
library(kableExtra)
library(wesanderson)
```

```{r}
#data
load("data/data.Rdata")
```

### final data cleaning
```{r}
DATA <- DATA %>%
  select(-c(student_id, EOC, grade))
```

### data budgeting
```{r}
set.seed(123)
DATA_SPLIT <- DATA %>%
  initial_split(strata = success)

DATA_TRAIN <- training(DATA_SPLIT)
DATA_TEST <- testing(DATA_SPLIT)

set.seed(234)
DATA_folds <- vfold_cv(DATA_TRAIN, strata = success)
DATA_folds
```

### prepping recipe
```{r}
DATA_rec <-
  recipe(success ~ ., data = DATA_TRAIN) %>%
  step_unknown(all_nominal_predictors()) %>%
  step_dummy(all_nominal_predictors(), one_hot = TRUE)

prep(DATA_rec) # checking prep
```

### tuning model
```{r}
xgb_spec <-
  boost_tree(
    trees = tune(),
    min_n = tune(),
    mtry = tune(),
    tree_depth = tune(),
    learn_rate = tune(),
    loss_reduction = tune()) %>%
  set_engine("xgboost") %>%
  set_mode("classification")

#workflow
xgb_workfl <- workflow(DATA_rec, xgb_spec)
```

### racing 
```{r}
library(finetune)
doParallel::registerDoParallel()

set.seed(345)
xgb_rs <- tune_race_anova(
  xgb_workfl,
  resamples = DATA_folds,
  grid = 20,
  metrics = metric_set(accuracy),
  control = control_race(verbose_elim = TRUE)
)
```

### Comparing models
```{r}
race <- plot_race(xgb_rs) 

race +
  labs(title = "Model Race",
        y = "Model Accuracy") +
  theme_minimal() +
  theme(plot.title = (element_text(hjust = 0.5)))
```

### extracting best model
```{r}
show_best(xgb_rs)
```

### making ROC curve
```{r}
xgb_last <- xgb_workfl %>%
  finalize_workflow(select_best(xgb_rs, metric = "accuracy")) %>%
  last_fit(DATA_SPLIT)

xgb_last$.metrics

 ROC_graph <- xgb_last %>%
  collect_predictions() %>%
  roc_curve(success, .pred_F) %>%
  ggplot(aes(x = 1 - specificity, y = sensitivity)) +
  geom_line(size = 1.5, color = "#5abcd6") +
  geom_abline(
    lty = 2, alpha = 0.5,
    color = "gray50",
    size = 1.2
  ) +
  labs(title = "ROC for Exploratory Model") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))
 
 ROC_graph
```

### confusion matrix
```{r}
DATA_pred_val <- collect_predictions(xgb_last)$.pred_class

model <- extract_workflow(xgb_last)

DATA_act <- DATA_TEST$success

confusionMatrix(DATA_pred_val, DATA_act)
```

### importance graph
```{r}
library(vip)
importance_graph <- extract_workflow(xgb_last) %>%
  extract_fit_parsnip() %>%
  vip(geom = "col", num_features = 10, mapping = aes(fill = Variable))

importance_graph +
  labs(title = "Importance of Variables for Pass/Fail") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none") +
  scale_fill_manual(values = wes_palette(name = "Darjeeling1", n = 10, type = "continuous"))
```

### dendrogram
```{r}
tree_fit <- extract_fit_engine(xgb_last)
library(DiagrammeR)
xgb.plot.tree(model = tree_fit, trees = 0)
```